// report entry period type
export const REPORT_ENTRY_PERIOD_TYPE_FINAL = "final";
export const REPORT_ENTRY_PERIOD_TYPE_QUARTER = "quarter";
export const REPORT_ENTRY_PERIOD_TYPE_SEQUENCE = "sequence";
export const REPORT_ENTRY_PERIOD_TYPE_SEMESTER = "semester";
export const REPORT_ENTRY_PERIOD_TYPES_HIGHSCHOOL = [
  REPORT_ENTRY_PERIOD_TYPE_FINAL,
  REPORT_ENTRY_PERIOD_TYPE_QUARTER,
  REPORT_ENTRY_PERIOD_TYPE_SEQUENCE,
];
export const REPORT_ENTRY_PERIOD_TYPES_UNIVERSITY = [
  REPORT_ENTRY_PERIOD_TYPE_FINAL,
  REPORT_ENTRY_PERIOD_TYPE_SEMESTER,
];

// report grade type
export const REPORT_GRADE_TYPE_AVERAGE = "average";
export const REPORT_GRADE_TYPE_REPORT = "report";
export const REPORT_GRADE_TYPES = [
  REPORT_GRADE_TYPE_AVERAGE,
  REPORT_GRADE_TYPE_REPORT,
];

// report table status
export const REPORT_TABLE_STATUS_DRAFT = "draft";
export const REPORT_TABLE_STATUS_PUBLISHED = "published";
export const REPORT_TABLE_STATUSES = [
  REPORT_TABLE_STATUS_DRAFT,
  REPORT_TABLE_STATUS_PUBLISHED,
];
