// Schedule type
export const SCHEDULE_TYPE_COURSE = "course";
export const SCHEDULE_TYPE_TP = "tp";
export const SCHEDULE_TYPE_TD = "td";
export const SCHEDULE_TYPE_PAUSE = "pause";
export const SCHEDULE_TYPE_EVENT = "event";
export const SCHEDULE_TYPES = [
  SCHEDULE_TYPE_COURSE,
  SCHEDULE_TYPE_TP,
  SCHEDULE_TYPE_TD,
  SCHEDULE_TYPE_PAUSE,
  SCHEDULE_TYPE_EVENT,
];

// Schedule day of the week
export const SCHEDULE_DAY_OF_THE_WEEK_MONDAY = "monday";
export const SCHEDULE_DAY_OF_THE_WEEK_TUESDAY = "tuesday";
export const SCHEDULE_DAY_OF_THE_WEEK_WEDNESDAY = "wednesday";
export const SCHEDULE_DAY_OF_THE_WEEK_THURSDAY = "thursday";
export const SCHEDULE_DAY_OF_THE_WEEK_FRIDAY = "friday";
export const SCHEDULE_DAY_OF_THE_WEEK_SATURDAY = "saturday";
export const SCHEDULE_DAY_OF_THE_WEEK_SUNDAY = "sunday";
export const SCHEDULE_DAY_OF_THE_WEEKS = [
  SCHEDULE_DAY_OF_THE_WEEK_MONDAY,
  SCHEDULE_DAY_OF_THE_WEEK_TUESDAY,
  SCHEDULE_DAY_OF_THE_WEEK_WEDNESDAY,
  SCHEDULE_DAY_OF_THE_WEEK_THURSDAY,
  SCHEDULE_DAY_OF_THE_WEEK_FRIDAY,
  SCHEDULE_DAY_OF_THE_WEEK_SATURDAY,
  SCHEDULE_DAY_OF_THE_WEEK_SUNDAY,
];

// Schedule repeat type
export const SCHEDULE_REPEAT_TYPE_DAILY = "daily";
export const SCHEDULE_REPEAT_TYPE_WEEKLY = "weekly";
export const SCHEDULE_REPEAT_TYPE_MONTHLY = "monthly";
export const SCHEDULE_REPEAT_TYPE_YEARLY = "yearly";
export const SCHEDULE_REPEAT_TYPE_ONE_TIME = "onetime";
export const SCHEDULE_REPEAT_TYPES = [
  SCHEDULE_REPEAT_TYPE_DAILY,
  SCHEDULE_REPEAT_TYPE_WEEKLY,
  SCHEDULE_REPEAT_TYPE_MONTHLY,
  SCHEDULE_REPEAT_TYPE_YEARLY,
  SCHEDULE_REPEAT_TYPE_ONE_TIME,
];
