// Student enroll origin
export const STUDENT_ENROLL_ORIGIN_ONLINE = "dashboard";
export const STUDENT_ENROLL_ORIGIN_PRE_ENROLL = "pre_enroll";
export const STUDENT_ENROLL_ORIGIN_PROMOTION = "promotion";
export const STUDENT_ENROLL_ORIGIN_RETROGRADE = "retrograde";
export const STUDENT_ENROLL_ORIGINS = [
  STUDENT_ENROLL_ORIGIN_ONLINE,
  STUDENT_ENROLL_ORIGIN_PROMOTION,
  STUDENT_ENROLL_ORIGIN_RETROGRADE,
];

// Student pre enroll status
export const STUDENT_PRE_ENROLL_STATUS_INITIATED = "initiated";
export const STUDENT_PRE_ENROLL_STATUS_PENDING = "pending";
export const STUDENT_PRE_ENROLL_STATUS_ENROLLED = "enrolled";
export const STUDENT_PRE_ENROLL_STATUS_REJECTED = "rejected";
export const STUDENT_PRE_ENROLL_STATUSES = [
  STUDENT_PRE_ENROLL_STATUS_INITIATED,
  STUDENT_PRE_ENROLL_STATUS_PENDING,
  STUDENT_PRE_ENROLL_STATUS_ENROLLED,
  STUDENT_PRE_ENROLL_STATUS_REJECTED,
];
