// Permission tables

// Other
export const PERMISSION_TABLE_COMMUNICATION = "communications";
export const PERMISSION_TABLE_CONTACT = "contacts";

// User
export const PERMISSION_TABLE_ROLE = "roles";
export const PERMISSION_TABLE_PERMISSION = "permissions";
export const PERMISSION_TABLE_USER = "users";

// School
export const PERMISSION_TABLE_SCHOOL = "schools";
export const PERMISSION_TABLE_DIRECTOR = "directors";
export const PERMISSION_TABLE_MANAGER = "managers";
export const PERMISSION_TABLE_TEACHER = "teachers";
export const PERMISSION_TABLE_STUDENT = "students";
export const PERMISSION_TABLE_PARENT = "parents";
export const PERMISSION_TABLE_YEAR = "years";
export const PERMISSION_TABLE_COURSE = "courses";
export const PERMISSION_TABLE_EXAM = "exams";
export const PERMISSION_TABLE_MEETING = "meetings";
export const PERMISSION_TABLE_QUIZ = "quizzes";
export const PERMISSION_TABLE_RESULT = "results";
export const PERMISSION_TABLE_REPORT = "reports";
export const PERMISSION_TABLE_SCHEDULE = "schedules";
export const PERMISSION_TABLE_REQUEST = "requests";
export const PERMISSION_TABLE_PAYMENT = "payments";

// Highschool
export const PERMISSION_TABLE_HIGHSCHOOL_SECTION = "highschool_sections";
export const PERMISSION_TABLE_HIGHSCHOOL_SPECIALTY = "highschool_specialties";
export const PERMISSION_TABLE_HIGHSCHOOL_CLASS = "highschool_classes";
export const PERMISSION_TABLE_HIGHSCHOOL_QUARTER = "highschool_quarters";
export const PERMISSION_TABLE_HIGHSCHOOL_SEQUENCE = "highschool_sequences";
export const PERMISSION_TABLE_HIGHSCHOOL_SUBJECT = "highschool_subjects";

// University
export const PERMISSION_TABLE_UNIVERSITY_FACULTY = "university_faculties";
export const PERMISSION_TABLE_UNIVERSITY_DEPARTMENT = "university_departments";
export const PERMISSION_TABLE_UNIVERSITY_DOMAIN = "university_domains";
export const PERMISSION_TABLE_UNIVERSITY_LEVEL = "university_levels";
export const PERMISSION_TABLE_UNIVERSITY_SEMESTER = "university_semesters";
export const PERMISSION_TABLE_UNIVERSITY_UNIT = "university_units";

// Aggregate list
export const PERMISSION_TABLE_LIST = [
  "*",
  PERMISSION_TABLE_COMMUNICATION,
  PERMISSION_TABLE_CONTACT,

  PERMISSION_TABLE_ROLE,
  PERMISSION_TABLE_PERMISSION,
  PERMISSION_TABLE_USER,

  PERMISSION_TABLE_SCHOOL,
  PERMISSION_TABLE_DIRECTOR,
  PERMISSION_TABLE_MANAGER,
  PERMISSION_TABLE_TEACHER,
  PERMISSION_TABLE_STUDENT,
  PERMISSION_TABLE_PARENT,
  PERMISSION_TABLE_YEAR,
  PERMISSION_TABLE_COURSE,
  PERMISSION_TABLE_EXAM,
  PERMISSION_TABLE_MEETING,
  PERMISSION_TABLE_QUIZ,
  PERMISSION_TABLE_RESULT,
  PERMISSION_TABLE_REPORT,
  PERMISSION_TABLE_SCHEDULE,
  PERMISSION_TABLE_REQUEST,
  PERMISSION_TABLE_PAYMENT,

  PERMISSION_TABLE_HIGHSCHOOL_SECTION,
  PERMISSION_TABLE_HIGHSCHOOL_SPECIALTY,
  PERMISSION_TABLE_HIGHSCHOOL_CLASS,
  PERMISSION_TABLE_HIGHSCHOOL_QUARTER,
  PERMISSION_TABLE_HIGHSCHOOL_SEQUENCE,
  PERMISSION_TABLE_HIGHSCHOOL_SUBJECT,

  PERMISSION_TABLE_UNIVERSITY_FACULTY,
  PERMISSION_TABLE_UNIVERSITY_DEPARTMENT,
  PERMISSION_TABLE_UNIVERSITY_DOMAIN,
  PERMISSION_TABLE_UNIVERSITY_LEVEL,
  PERMISSION_TABLE_UNIVERSITY_SEMESTER,
  PERMISSION_TABLE_UNIVERSITY_UNIT,
];
